plugins:
  - jekyll-figure
  - jektex
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  title: ":title - page :num"
permalink: pretty
exclude:
  - CNAME
  - CONTRIBUTING.md
  - pyproject.toml
  - README.md
  - uv.lock